
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>revan</title>
    <link rel="stylesheet" href="../css/bootstrap.css">
    <link rel="stylesheet" href="../css/styles.css">
    <?php include '../cookie.php';
    ?>
   
   
</head>
<body>

<?php include '../top.php'; ?>
<div class="icon">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title">
                    <div class="info">
                        <h2>Darth Revan</h2>
                        <img src="../images/sith-lord/revan.jpg" alt="">
                        <p>Revan—renowned as the Revanchist, dreaded as the Dark Lord of the Sith Darth Revan, and hailed as the Prodigal Knight—was a human male who played pivotal roles as both Jedi and Sith across centuries of Old Republic conflicts, including the Mandalorian Wars, Jedi Civil War, Galactic War, and Revanite Crisis.</p>
                        <p>Believed to have been born around 3994 BBY in the Outer Rim Territories, the child later known as Revan was found by the Jedi Order and apprenticed to the Jedi Master Kreia. The Padawan had an insatiable hunger for knowledge and soon rose to be the Jedi's most promising pupil. Alongside his friend Malak, he became a charismatic critic of the Order's inactivity in the ongoing Mandalorian Wars between the Galactic Republic and the Mandalorian Neo-Crusaders. In defiance of the Jedi Council, the Knight took upon the name Revan and started the Revanchist movement to combat the Mandalorians as the Republic Military's Supreme Commander. Revan and his forces gradually pushed back the Mandalorians, saving countless worlds at the price of devastating moral compromises and the embrace of dark side practices. On Malachor V, Revan defeated the Mandalorian leader Mandalore the Ultimate in single-combat and ordered the activation of the Mass Shadow Generator superweapon, destroying both armies and the planet but winning the war in the process.</p>
                        <p>Revan and Malak, now hailed as the greatest of heroes, vanished into the Unknown Regions to investigate a mysterious Sith influence behind the war. They discovered a hidden Sith Empire and fell under the thrall of the Sith Emperor Vitiate. Vitiate directed the newly anointed Darth Revan and Darth Malak to find the mystical Star Forge to escalate plans of a galactic invasion, but the pair broke free from his mind control and used the Star Forge for themselves—creating their own Sith Empire and a fleet of warships. Intent on unifying the galaxy to destroy the lurking Sith menace, they returned to the galaxy as conquerors and battled the Jedi and the Republic in the resultant Jedi Civil War. Revan almost succeeded, but Malak usurped the throne and fired aboard his flagship during a Jedi ambush led by Bastila Shan. Revan nearly died, but Bastila healed him and took him before the surviving Jedi for judgment.</p>
                        <p>The Jedi Council wiped Revan's mind and soon retrained him as a Jedi tasked to locate the Star Forge. Revan picked up many allies and fell in love with Bastila across his journeys. Malak eventually intercepted the team and revealed to Revan his true identity as the former Dark Lord, then captured and corrupted Bastila to the dark side. In a last stand, Revan led the remaining Republic fleet against the Star Forge, redeemed Bastila back to the light side, and killed Malak in battle, destroying the Sith Empire he created. Revan married Bastila and sank into obscurity until visions from his past led him to rediscover Vitiate's Sith Empire. Alongside his former protégé Meetra Surik, also known as the Jedi Exile, and the Sith Lord Scourge, Revan attempted to assassinate the Emperor. However, Scourge betrayed the pair, killing Meetra and helping Vitiate imprison Revan in stasis.</p>
                        <p>Revan waged telepathic war against the Emperor for three-hundred years, influencing him into stalling his Sith invasion at terrible cost to his own psyche. Revan eventually escaped captivity and took control of the Foundry space station to create an infinite army against the Empire, but he was thwarted and killed by an Imperial strike team. However, with his mind splintered across centuries of torture, his darker half rejected death and resolved to destroy Vitiate. The Emperor's body had recently been killed in battle, but his spirit lingered, so Revan sought to resurrect him to a physical form to permanently destroy him. A coalition of Imperial and Republic forces, fearing that Revan's meddling would only bring untold destruction, united with Revan's light side spirit to defeat him and an army of fanatical Revanite followers on Yavin 4. Although Vitiate fed off the battle and escaped into the galaxy, the two Revans merged together in peace into the Force. Revan's unified spirit pushed onward, eventually guiding a wayward Scourge to destroy the Emperor's original—and final—body and doom his spirit to chaos. Revan later joined with the legendary Alliance Commander and many of history's greatest champions to battle the reassembling vestiges of Vitiate's essence, destroying the Emperor once and for all.

Three millennia later, the Sith Lord Darth Bane discovered Revan's Sith Holocron and used its teachings to destroy the reigning Brotherhood of Darkness and as inspiration for the Rule of Two.</p>
                        <h3>Biography</h3>
                        <p>A Human male, the individual later known as Revan was born in approximately 3994 BBY, and some believed that he had been born in the Outer Rim Territories. The child who would be remembered as Revan was eventually discovered to be Force-sensitive and was accepted into the Jedi Order. The Jedi Master Kreia claimed to have been his first teacher in the ways of the Force. Regardless of the truth of her statement, the Human was trained along with a fellow student named Alek on both the planet Coruscant and at the Jedi Enclave on the planet Dantooine. Both Humans received further training from the Twi'lek Jedi Master Zhar Lestin, who noted that the future Revan possessed what he described as an insatiable desire for knowledge. Lestin believed that it was simply youthful exuberance and eagerness, and he expected the young man to become a champion of the Order—a sentiment shared by Master Vandar Tokare, though Master Vrook Lamar was wary of the student's desire for knowledge.</p>
                        <p>The Jedi studied under a number of Jedi Masters after leaving the tutelage of his first teacher, learning from Master Lestin, the Enclave's chronicler Master Dorak, and Arren Kae. The former Jedi hopeful Mical later claimed that Revan had undertaken a thorough study of Force bonds and other uncommon Force powers during his time as a Padawan. Alongside Alek, the future Revan achieved the rank of Jedi Knight sometime before the year 3964 BBY, and the two were widely acknowledged as being among the most promising members of the Jedi Order. However, Alek's friend was commonly recognized as the more powerful and intelligent of the pair, and he was seen as the leader among the two. By 3964 BBY, the man was a well-known, charismatic, and powerful Jedi Knight. According to Mical, Revan returned to his first teacher in order to learn how to best leave the Jedi Order, though he did not follow through.</p>
                        <h4>The Mandalorian Wars</h4>
                        <p>That year, warriors of the Mandalorian culture began an invasion of the Galactic Republic's territories in the Outer Rim, bringing the Mandalorian Wars to the larger galaxy. Outraged at the Jedi Council's refusal to involve the Order in the conflict, the young Jedi Knight began to move among the Order, arguing that the Jedi should actively aid the Republic Military in its fight against the Mandalorian Neo-Crusaders. The Republic media branded him as the "Jedi's own crusader," and the "crusader" gradually gathered a following of like-minded Jedi as the number of military and civilian casualties continued to rise. Alek was the first to join the cause, and his friend soon became considered to be the honorary "Master" of those who followed him.</p>
                        <p>With the backing of Alek and his other followers, the Jedi Knight decided to journey to the war front against the wishes of the Jedi High Council so that he could scout the enemy lines. On the way, he and his followers stopped on the planet Taris in the Ojoster sector in order to meet with the Jedi Master Lucien Draay. The "crusader" hoped to recruit more Jedi to his cause from the Jedi Tower on Taris, but neither Draay nor any of the other Jedi there were willing to oblige. Not long after departing Taris, the Knight left Alek and the majority of his followers on the planet Suurja while he himself investigated Mandalorian activity on Onderon and its moon Dxun. However, many of his followers were captured by Mandalorians in an ambush at Suurja. Considering his findings to be "disturbing," the Knight reported his findings to the Jedi Council on Coruscant shortly after the Republic officially entered into the Mandalorian Wars, though the Council once again told him that the Order had no place in the war. In response, the Council dispatched the Human Knight on a mission to rescue those Jedi who had been captured. As he departed the Council chambers on Coruscant, the Knight encountered Master Draay and, after a brief conversation about their views on the war, he departed to complete his assignment.</p>
                        <p>The Jedi's followers, including Alek, were eventually rescued from the Mandalorian scientist Demagol on the planet known as Flashpoint by the fugitive Jedi Padawan Zayne Carrick, who had been framed by his former Master Lucien Draay for murdering his classmates on Taris. Once reunited with Alek and his followers, the Knight continued his campaign for Jedi intervention in the Mandalorian Wars. Finding himself to be a celebrity to the larger Republic as the head of the Revanchist movement—as his faction became known—he was cast by the Republic media in the role of a crusading savior who was wrongfully ignored by the Jedi Council. Though he was first referred to as "the Revanchist Leader" in news reports, the young Jedi Knight soon became known simply as "the Revanchist."</p>
                        <p>Over the course of the year 3963 BBY, the Revanchist continued to travel the galaxy and bring his message of Jedi intervention to all who would listen. A Cathar Jedi named Ferroh, one of the Revanchist's followers, brought the planet Cathar to the Revanchist's attention. Ferroh's entire species had vanished from their homeworld ten years prior, and the Revanchist—believing that the Mandalorians were responsible—began showing other Jedi the abandoned world in order to convince them that the Mandalorians needed to be stopped. He and Alek were on Cathar when Mandalorian forces under the command of their leader Mandalore the Ultimate attacked the planet Serroco. In the Battle of Serroco, the Mandalorians bombed the planet's surface with nuclear warheads, and the Revanchist felt the death of thousands of innocents from several sectors away. Not long afterward, The Revanchist was invited by Lord Arkoh Adasca, the head of the Adasca BioMechanical Corporation of Arkania, to bid on weaponized exogorths that the businessman sought to sell to any faction in the Mandalorian Wars. The Knight was unable to attend the auction due to pressing business elsewhere, so he sent Alek in his place. Several Jedi had visions that Adasca's exogorths could change the course of the war, so the Revanchist instructed his friend to ensure that the danger the weapons posed was eliminated. In the aftermath of the Adasca affair, the Revanchist was rumored to be arranging a meeting between several Jedi opinion-makers.</p>
                        <p>Shortly after the Adasca affair, the Taris Siege, and the bombardment of Jebble, Lucien Draay was appointed to the Jedi Council. He reported to the Council that Republic intelligence reports indicated that there was a blow to the Mandalorians' plans of conquest, reportedly by an insurrection within their own ranks, and stated that the "interventionist path" sought by the Revanchist was wrong for both the Republic and the Jedi. The Council approved his motion, which ordered the recall, or if necessary, detention, of the Revanchists. The Jedi Council sent Alek back to the Revanchist and his followers with a final warning after Alek, now going under the guise of "Captain Malak," testified to the Jedi Council against the secret cabal known as the Jedi Covenant.</p>
                       
                        <h4>Rise of the Sith</h4>
                        <p>In the weeks that followed, Revan ordered that the remaining Mandalorians be stripped of their weapons and armor, and that they dismantle their basilisk war droids. Knowing that they would only resume the fight if a new leader took Mandalore the Ultimate's place, Revan refused to return the Mask to the Mandalorians, and many of the warriors soon became bounty hunters or mercenaries. Shortly after the Battle of Malachor V, Revan completed a new assassin droid named HK-47, which he based on the Czerka Corporation's HK-24 series assassin droid.[8] Not wanting to repeat the devastation that occurred at Malachor, Revan decided to use HK-47 in order to assassinate selective opponents. When analyzing Revan's actions during the Mandalorian Wars and particularly at Malachor, HK-47 came to believe that Revan may have had an ulterior motive—the droid believed that the devastation was meant to "break" the Jedi and make them loyal to Revan alone.</p>
                        <p>After Malachor, Meetra Surik was left bereft of a connection to the Force, and she decided to answer the Jedi Council's demands for Revan, Malak, and Surik to answer for their actions. However, Revan and Malak refused and took the remainder of their forces into the Unknown Regions, claiming to be pursuing the remaining Mandalorians. Malak urged Revan to kill Surik, but Revan refused, claiming that the Jedi was "already dead." Revan took Malak alone to Rekkiad, where they followed Mandalore's directions to the twin ice structures known as the Twin Spears. There, they discovered the tomb of the Sith Lord Dramath the Second and a datacron within his sarcophagus that confirmed Mandalore's tale. The datacron spoke of a planet named Nathema, and the two Jedi decided to travel there in order to seek out the Sith who had manipulated Mandalore. Before departing, Revan left Mandalore's Mask in Dramath's sarcophagus to ensure that the Mandalorians did not rediscover it.</p>
                        <p>Revan and Malak traveled alone to Nathema, which was a world in the distant Chorlian sector, and they were astonished to discover that the planet was completely barren of the Force. There, the two Jedi learned the story of the Sith Lord Vitiate, who had lived around the time of the Great Hyperspace War between the Republic and the Sith Empire a thousand years earlier. In 4999 BBY, Vitiate had convinced many of the remaining Sith to join him in a ritual of Sith magic, but the Ritual of Nathema had resulted in the extinction of all life on the surface of Nathema and the immortality of Vitiate, who took on the name of Sith Emperor and gathered the younger generations of Sith before departing the remains of the shattered Sith Empire.</p>
                        <p>Determined to locate the Sith threat, Revan and Malak followed the Sith survivors' trail to the storm-covered world of Dromund Kaas, which they discovered to be the capital of a new Sith Empire. Posing as mercenaries, the pair spent months learning everything they could about the Empire and its ruler, and they soon uncovered the Emperor's plans for an invasion of the Republic. But instead of warning the Republic, the two Jedi—proud and overconfident—believed that they could defeat the Emperor alone, and they looked for a way to infiltrate the Imperial Citadel in the Empire's capital city of Kaas City so that they could confront the Sith ruler. The pair received aid from Yarri, a member of the Imperial Guard who protected the Emperor, but the Jedi were unaware that all Guardsmen were bound to the Emperor's will and that she was leading them into a trap.</p>
                        <p>When Revan and Malak arrived at the Emperor's throne room, the Sith ruler was ready for them—instead of fighting them, the Emperor reached out and dominated their minds, twisting the pair into willing servants and completing their fall to the dark side before he scoured their minds for useful information. Anointing his new servants as Darth Revan and Darth Malak, the Dark Lords of the Sith, the Emperor sent them back to the Republic as a vanguard to his own invasion, ordering them to make use of the Rakatan Star Forge and to report back when they had crushed the Republic's resistance. Publicly, the Emperor announced that Revan and Malak had been Republic spies, showing images of the pair to his people and proclaiming that they had been executed in the depths of the Citadel.</p>
                        <h3>Personality and traits</h3>
                        <p>Revan was a Human male with fair skin and brown eyes, and he wore his dark brown hair at shoulder-length for much of his life. In Revan's own opinion, his features were unremarkable and average. Revan grew a beard during the search for the Star Forge, though when he shaved it off shortly after the Battle of Rakata Prime, he was able to pass unrecognized through the throngs of people on Coruscant. Even as a young apprentice, Revan was known for his remarkable intelligence and exceptional charisma, as well as an insatiable desire for knowledge. A military genius, Revan was renowned for his tactical thinking and decisive leadership even as a Jedi Knight. In his youth, Revan was outraged by the Jedi Council's indecision and refusal to act against the Mandalorians, and his desire to defend the Republic led him to argue vociferously for his cause. His determination and charisma gained him a following of like-minded Jedi, though his strength and leadership led the others to accept him as their leader without question.</p>
                        <p>When he finally joined the Republic Military in the war against the Mandalorians, Revan began to change. Over the course of the Mandalorian Wars, Revan became more and more cold and calculating, adopting the militant mindset of his enemies in order to win his battles. By the end of the war, Revan was more than willing to sacrifice allies and his citizens in order to gain or preserve an advantage over his opponent. Exposed to the teachings of the Sith, Revan and Malak utilized an untested weapon like the mass-shadow generator even with the possibility that the weapon might harm their own fleet.[2] Before each battle, Revan would stare at his reflection in a mirror while wearing his mask and recited the Jedi Code repeatedly until the words seemed to blur together.</p>
                        <h3>Powers and abilities</h3>
                        <p>Even at an early age, Revan's insatiable hunger for knowledge and mastery over the Jedi arts drove him to be the Order's most powerful champion against the Mandalorian threat. In his prime, Revan was an unstoppable force on the battlefield, skilled in multiple forms of lightsaber combat, and regarded by many as the greatest warrior of his age. He accumulated respect from a vast range of different cultures from the Mandalorians to the Echani—the Rakata to the ancient Sith. However, despite his skills, he was unable to overcome the numerous powerful strike teams that challenged him later in life, nor the conflicts rising and tearing him apart within his very own heart and soul, thus leading to his downfall.</p>
                        <p>Revan was the most powerful Jedi of his era. During the Mandalorian Wars, Revan was considered the Jedi Order's greatest champion. After becoming a Sith Lord, Revan's command of the Force grew as he studied the ancient practices of the dark side. Following his redemption, Revan was stronger than ever before, now having a unique understanding of the Force. His mastery allowed himself to open up to both sides of the Force simultaneously, summoning such power that he could then unleash the Force in its purest form. Even after three centuries of imprisonment and torture, Revan's dominance over his contemporaries continued, only ever being truly rivalled by the Sith Emperor Vitiate.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 
  <?php include '../bottom.php'; ?>