
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>nihilus</title>
    <link rel="stylesheet" href="../css/bootstrap.css">
    <link rel="stylesheet" href="../css/styles.css">
    <?php include '../cookie.php';
    ?>
   
   
</head>
<body>

<?php include '../top.php'; ?>
<div class="icon">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title">
                    <div class="info">
                        <h2>Darth Nihilus</h2>
                        <img src="../images/sith-lord/nihilus.jpg" alt="">
                        <p>Darth Nihilus (pronounced /ˈnaɪ.ə.lɨs/) was a Human male who reigned as a Dark Lord of the Sith during the era of strife following the Jedi Civil War. Before becoming a Sith Lord, he lost everything during the Galactic Republic's war against the Mandalorian Neo-Crusaders. He survived the activation of the Mass Shadow Generator superweapon during the war's final battle at the planet of Malachor V, which surrounded the planet with a destructive spatial phenomenon known as a mass shadow. Experiencing the shadow that obliterated almost everything on and around the planet made Nihilus crave Force energy. The affliction painfully ravaged his body while rendering him a wound in the Force. He was found by a seeker of these, the former Jedi Kreia, who became the Sith Lord Darth Traya and told him that she could teach him to feed his endless hunger. He accepted her offer of apprenticeship at the Trayus Academy on Malachor V, where he, over time, became one of three concurrent Dark Lords of the Sith.</p>
                        <p>Together, they formed a triumvirate with Darth Traya at its head and her other apprentice, Darth Sion, as the third member. The trio chose individual titles for themselves, Darth Nihilus becoming the Lord of Hunger. The apprentices grew in strength throughout their training and eventually overpowered their Master. Sion defeated Traya, while Nihilus sapped her energy. The two Sith then combined power to sever her connection to the Force and sent her into exile. Nihilus' affliction developed to the point where the Dark Lord was forced to call upon the dark side of the Force to encase his spirit within his mask and armor to stay alive. He and Sion then began a Jedi purge, causing the virtual extinction of the Jedi Order. Nihilus was responsible for the devastation of the planet Katarr in 3952 BBY, killing and absorbing the Force energy of the Jedi at the Conclave on Katarr along with every other living thing on the world save one Miraluka woman named Visas Marr. Marr was collected from the surface and Nihilus began to train her as his Shadow Hand.</p>
                        <p>One year later, Nihilus sensed a growing presence in the Force and sent Marr out to eliminate it. That presence was a female exiled from the Jedi Order, Meetra Surik, who was on a quest to find the few Jedi Masters who had survived the Purge with the aide of Darth Traya, who had put away her Sith trappings and identified herself once more as Kreia. When Marr attempted to assassinate Surik, the exiled Jedi defeated her and convinced her to turn to the light side of the Force in the process. Although Nihilus returned to lurking the fringes of known space, he was eventually tricked by Kreia into initiating the Battle of Telos IV in an attempt to absorb a Jedi Academy that lacked any Force-sensitives aside from the headmistress. Nihilus met a large Republic and Mandalorian fleet at Telos IV that distracted him. Meanwhile, his flagship, the Ravager, was secretly boarded by a small force consisting of Surik, Marr, Mandalore the Preserver, and his Mandalorians. The trio confronted and slew Nihilus in the ensuing duel while the Mandalorians rigged explosives that destroyed the ship. The Sith Lord's armor maintained his spirit and was collected for burial on the Sith homeworld of Korriban, where his soul could be contacted with a holocron of his own creation.</p>
                        <h3>Biography</h3>
                        <p>The Human male who would one day be known as Darth Nihilus, Dark Lord of the Sith, was alive at the conclusion of the Mandalorian Wars, a galaxy-wide conflict between the Mandalorian Neo-Crusaders and the Galactic Republic. Amidst those battles, he lost everything: his family, friends, as well as his will to live. He was on the planet of Malachor V during the final battle of the war in 3960 BBY, when Jedi General Meetra Surik gave the order to activate the Republic's Mass Shadow Generator superweapon. The generator killed almost everyone on the planet's surface and in orbit nearby.</p>
                        <p>The future Dark Lord survived the superweapon's destruction of the surface and assumed a dark persona while grieving his losses, in part as a means of survival. He was trapped on the planet by the artificially-created mass shadows along with the bulk of the opposing, disabled fleets that filled space around the planet—where the Mandalorians had committed all of their forces in a last attempt at defeating the Republic—and took ill suddenly due to the shadows' effects. His emotional pain then manifested as an emptiness that swept over his idle body and it soon began to manifest as an intense "hunger." Without intent, he drained the life-force of another survivor. The act was an unpleasant experience for him, but the hunger and his painful memories faded for a brief moment alongside his sickness. Nonetheless, the emptiness returned more relentless and severe than before. He indulged in absorbing the energy of other survivors, but, the more he fed, the shorter the hunger was appeased and the more powerful it became.</p>
                        <p>After the Dark Lord of the Sith Darth Malak was killed at the Jedi Civil War's conclusion in 3956 BBY, the Sith Empire became divided and its followers turned on each other, with many factions rising to stake claim to what little power could be garnered. The man was eventually discovered by the Dark Lord Darth Traya, who had sensed him as a wound in the Force. After locating him, Traya explained that it was the Force that fueled his hunger and offered to train him to devour entire worlds to help appease the hunger at her school on the planet, the Trayus Academy. He followed her there and learned the ways of the Sith alongside another prospective Sith. Traya's hungry pupil and her other apprentice each honed different aspects and skills of the dark side of the Force, until they both became Sith Lords. The man took up the name Darth Nihilus, while the second apprentice became known as Darth Sion, and they joined with Traya in the creation of a Sith Triumvirate. In addition, the three each took a unique title, with Nihilus selecting "Lord of Hunger."</p>
                        <p>Darth Traya perceived Nihilus' hunger for the Force as detrimental to the Sith's goals. Nevertheless, she taught him how to harness that hunger to make him stronger for a time, as she had promised. Nihilus consumed planets on several occasions, caring only to appease his hunger, allowing the dark side to consume him more and more each time he indulged his ever-intensifying hunger. Alongside his hunger, his power also grew dramatically, until he eventually surpassed his Master. Their views on how to destroy the Jedi Order also became divided, with Sion and Nihilus wanting to destroy them outright while Traya desired a more time-consuming approach. This strained the Triumvirate's already fragile alliance to the breaking point. In 3955 BBY, Nihilus and Sion combined forces to challenge Traya, confronting their teacher in the center of her own Academy. Sion and Nihilus entered the Core and ambushed Traya. Nihilus Force-pushed her into a feature of the platform, after which Sion larruped her into submission. Sion combined his power with Nihilus' to sap Traya's Force energy, cutting her off from the Force before casting her out into exile.</p>
                        <p>With Traya gone, the Sith were left with no defined leadership and her followers fractured into many factions once again, all seeking to claim scarce power. Meanwhile, the two Sith Lords went about destroying the Jedi Order together, though they did so separately and with different vehicles. On the one hand, Sion killed as many Jedi he could find. On the other, Nihilus traveled the fringes of known space with a large fleet of ships that he had ripped from the mass shadows surrounding Malachor V. He made one such vessel, the Ravager, his flagship and led his flotilla to the largest deposits of Force energies he could find, whereupon he sated the hunger within him and further increased his power. Both Nihilus and Sion were successful in their pursuits and they extinguished the Jedi. Four years after Traya's exile, Nihilus and Sion, having been the ones who defeated her, reunited the fractured Sith to take control.</p>
                        <p>Nihilus became so absorbed by the dark side of the Force and his hunger that his physical body began to erode. Knowing that he would succumb to death if he did not act soon, Nihilus ripped his spirit from his body and encased it in the armor he wore, thus allowing the dark side to consume his useless body. Using the Force, the Sith Lord was able to keep his robes, armor and mask together, giving him some form while allowing him to use his Force powers as well as a lightsaber. Apart from that, he no longer had a physical form and became simple, primitive intent. Additionally, the Dark Lord constructed a cubic holocron at some point that contained a sum of Sith knowledge and a number of their secrets.</p>
                        <h3>Legacy</h3>
                        <p>After Nihilus' death, Meetra Surik traveled to Malachor V for a final meeting with Kreia, completing her own training with the death of the former Sith. In reaching her mentor, Surik killed the last of the Sith, Darth Sion, convincing the continually suffering Sith Lord to let go of his life. Nonetheless, the Sith lived on after the fall of the Sith Triumvirate. At least one Sith Lord rose and succeeded Nihilus, quietly ruling as the Republic began to thrive anew. Similarly, the Jedi Order rebounded as well, with Marr and other Force-sensitive companions of the Exile rebuilding it. In 3681 BBY, the Sith and Jedi would once again clash during the Great Galactic War that pitted the Republic against a resurgent Sith Empire. In the aftermath of that conflict, the two shared an uneasy coexistence during the Cold War that began in 3653 BBY. The subsequent decades saw replicas of Nihilus' mask and cowl worn by galactic citizens.</p>
                        <h3>Personality and traits</h3>
                        <p>Darth Nihilus was a man who always craved greater power. However, unlike most Sith Lords, he cared very little for the Sith as an organization. Nihilus saw death as the sole purpose of life, and power as the means to achieve it. He was cautious, as his actions during the campaign against the Jedi showed, and was known as an aggressive, dominant figure who would not abide a threat to his power.</p>
                        <p>Nihilus was once a Human male with black hair coiled finely into strips that he tied together behind his head. After he indulged his hunger for the dark side he lost his corporeal form, preserving his existence only by having his spirit linger within his mask and armor. The Dark Lord fully embraced his condition, as the mysterious and monstrous facets of it instilled in people who met him a deep-rooted fear upon which he could prey. Ceasing to feel fear and other emotions, he became an entity of pure intent. Nonetheless, Nihilus was still Human enough to have some feelings, as his bond with Marr persisted until their confrontation on the Ravager. She was his only apprentice, and her betrayal was met with much anger.</p>
                        <h3>Powers and abilities</h3>
                        <p>During combat, Darth Nihilus fought in an aggressive, one-handed style. He had learned some of the greatest of the Sith teachings, but such practices took the form of dependence. They would make him stronger, but only for a time, and he would have to feed upon Force energy to replenish his strength. For this reason, Force-sensitives and worlds rich in the Force would draw him. His reach in the Force eventually extended to a point where he could feel Force users throughout the galaxy to find planets he would then cleanse entirely, killing everything who was touched by the Force. Prolonged use of this power made him a threat to all life, as his craving grew more intense with each feeding. Eventually, Nihilus' hunger controlled him, not the other way around, and the Sith Lord would instinctively feed upon those around him, slowly killing them. Nihilus' very speech caused pain and death to all who heard it, and those who served him became utter slaves in time. His ability was somewhat similar to Traya's influence upon others: the reconvened Jedi Council in the Jedi Enclave on Dantooine inferred that the Sith had somehow learned this ability to feed on the Force from her.</p>
                        <p>Darth Nihilus was adept in many aspects of the Force. He used his dark variant of the Sever Force ability to betray Darth Traya alongside Darth Sion by stripping her of the Force and casting her out of the Sith Order. Nihilus could also use the Force to lift starships, as he did on Malachor V with the Ravager. He tore it from the mass shadows that surrounded the planet and kept it together even though it had suffered extensive structural damage. Through the Force, Darth Nihilus was able to escape death by containing his consciousness in his armor—an ability that Darth Krayt would inquire of Nihilus' holocron millennia later. He was also proficient in Dark rage, Farsight, Force lightning, Force resistance, Force scream, and Force whirlwind, among others, such as a dark variant of Force healing called Dark Healing. His knowledge also extended to Sith alchemy: during the second battle of Onderon, Nihilus' sect of Sith followers used techniques that would bend tame beasts to their will. Nihilus could increase the strength of Force powers he used greatly, if he wished, and he was capable of reaching through the Force at a range as far as a star system.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 
  <?php include '../bottom.php'; ?>