
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new-jedi-history</title>
    <link rel="stylesheet" href="../css/bootstrap.css">
    <link rel="stylesheet" href="../css/styles.css">
    <?php include '../cookie.php';
    ?>
   
   
</head>
<body>

<?php include '../top.php'; ?>
<div class="icon">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title">
                    <div class="info">
                        <h2>Jedi Order</h2>
                        <img src="../images/newjedi.png" alt="">
                        <p>The Jedi Order, also known as the New Jedi Order under Jedi Master Luke Skywalker, was a noble religious order of protectors united in their devotion to the light side of the Force. With a history dating back thousands of years before the rise of the Galactic Empire, the Jedi Knights—noted for their lightsabers and natural ability to harness the powers of the Force—stood as the guardians of peace and justice in the Galactic Republic. The Order was originally established on Ahch-To in the Unknown Regions. In later years, the Jedi Grand Temple on the Core World Coruscant served as the hub of all Jedi activity in the galaxy. The Temple was also a training school for younglings and Padawans, who learned the ways of the Force under the supervision of Jedi Masters, twelve of whom were elected to serve on the Jedi High Council—the Order's highest governing authority. The High Council's staff officers were the Grand Master, who functioned as the leader of the Order and was a title reserved for the wisest Jedi Master, and the Master of the Order, who served as the Council's appointed leader. The Jedi Code governed the Order's way of life; therefore, every Jedi was duty-bound to observe and uphold the Code or else risk banishment from the Order's ranks.</p>
                        <p>Following the Battle of Endor, the Alliance General Han Solo and the former Princess of Alderaan, Leia Organa, were married[106] and after the defeat of the Empire at Jakku, they had a son named Ben Solo. Ben was Luke Skywalker's nephew, as Organa was his twin sister, a fact Skywalker only learned from the Force spirit of Obi-Wan Kenobi following Yoda's death. On Ajan Kloss, Skywalker trained Organa in the ways of the Jedi as his first student. She even constructed her own lightsaber, but after seeing a vision of her son's death as the culmination of her Jedi training, Organa declined to progress further. She then directed her focus to the future of the New Republic.</p>
                        <p>Around five years after the Battle of Endor, Skywalker helped rescue Grogu, a mysterious alien that shared the same species as Yoda. The alien had previously demonstrated many remarkable feats in the Force. Skywalker expressed his desire to train the individual in the ways of the Force. He carried Grogu and proceeded to leave accompanied by R2-D2.</p>
                        <p>Skywalker began training his nephew in the ways of the Force at Organa's behest. In many ways, Solo reminded his parents of his grandfather, Vader, therefore Organa wanted him to train with his uncle in the hope that he would not turn to the dark side as well. In addition to Solo, Skywalker recruited several other students including Hennix, Tai, and Voe during his visits to many worlds over two decades. During this time, Solo was trained in lightsaber combat and became skilled with the Jedi weapon. The Jedi Temple of Luke Skywalker was founded as a training center for a generation of new Jedi all looking to the guidance of one master.</p>
                        <p>While the younger Solo was still an adolescent, Skywalker traveled with his nephew and Lor San Tekka to the Jedi outpost on Elphrona seeking Jedi artifacts. The trio were accosted by a dark side sect known as the Knights of Ren. Master Skywalker used his Force powers to defeat the Knights. Before leaving, the Knights' leader Ren told Solo to contact the Knights should he ever consider exploring the dark side further.</p>
                        <p>Solo's family would ultimately learn that he was gradually seduced to the ways of the dark side through the machinations of the First Order's ruler, Supreme Leader Snoke. Organa blamed Snoke as the sole cause of her son's descent into darkness, culminating in the destruction of the Jedi Temple, but Skywalker felt responsible for his nephew's fate. Sensing the dark side's influence within Solo, Skywalker probed his nephew's mind and beheld visions of the dark warrior that he was becoming. Skywalker instinctively raised his lightsaber to kill his nephew while he slept, believing Solo would destroy all that he loved; however, he stopped himself from killing his sister's son, and was overcome by shame. He then saw that Solo had awoken. He saw fear in the eyes of his young nephew, and in that moment Skywalker felt he had failed as a Jedi Master.</p>
                        <p>Solo reached for his blade and razed the hut using the Force, collapsing it in on his uncle. As Solo struggled to comprehend the situation and lost control of his emotions, the Jedi Temple was destroyed by a powerful storm, killing most of Skywalker's other students. Shortly later, Hennix, Tai and Voe returned from an offworld trip. They confronted Ben Solo, who told them that Skywalker had tried to murder him. Skeptical, they tried to detain him but Solo fled following a brief skirmish and sought Snoke. Hennix, Tai and Voe resolved to find Solo and investigate what had happened. Meanwhile, Solo sought out Snoke and the two decided to seek out the Knights of Ren.</p>
                        <p>Traveling to the Jedi outpost on Elphrona, Solo contacted Ren, who told him to find the Knights of Ren on Varnak. However, Hennix, Tai and Voe caught up with the fugitive Solo. Though Tai preferred to reason with Solo, Voe and Hennix fought him, believing that he had a role in destroying the Jedi Temple and killing their brethren. Solo killed Hennix in self-defense before fleeing to Varnak. However, Ren was still unsatisfied that Solo was worthy to become a Knight of Ren but took him on a trial run.</p>
                        <p>To test Solo's worthiness for the dark side, the Knights of Ren enlisted his services in obtaining a Force relic called the Mindsplinter from a group of Mimbanese on the Minemoon. Using Tai's connection to Solo, Tai and Voe tracked him down there. During the ensuing skirmish, Tai tried to reason with Solo but was murdered by Ren, who deemed him unworthy. Consumed by rage and grief, Solo killed Ren and Voe, embracing the dark side. Taking the path of darkness, Solo became the Master of the Knights of Ren, adopting the name "Kylo Ren" and bleeding his kyber crystal.</p>
                        <p>Solo turned to the dark side of the Force and became an apprentice of Snoke, joining the First Order and the Knights of Ren in the process and taking on the new identity of Kylo Ren. By the time of the outbreak of the First Order/Resistance War, Ren had gained a reputation of a "Jedi killer" due to Ren's skills with his lightsaber and his role in destroying Skywalker's new Jedi and his hopes of fully restoring the Jedi Order. Ren had become obsessed with fulfilling the legacy of his grandfather, but recognized him by his dark persona of Darth Vader rather than that of the redeemed Anakin Skywalker.</p>
                        <p>Skywalker regained consciousness in the rubble of his nephew's hut too late to prevent Solo's destruction of the Jedi temple and the deaths of the students inside. Solo had already fled, and Skywalker could only witness his temple still burning alongside his astromech droid, R2-D2. Skywalker felt responsible for the ordeal and decided to exile himself, although those closest to him learned that he was also searching for the first Jedi Temple. Skywalker only left traces of his location in a single star map, with the remaining data being present in old Imperial records. Skywalker eventually found the first Jedi temple on the aquatic world of Ahch-To, where he took up refuge and lived in exile as a hermit.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 
  <?php include '../bottom.php'; ?>