
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>satele-shan</title>
    <link rel="stylesheet" href="../css/bootstrap.css">
    <link rel="stylesheet" href="../css/styles.css">
    <?php include '../cookie.php';
    ?>
   
   
</head>
<body>

<?php include '../top.php'; ?>
<div class="icon">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title">
                    <div class="info">
                        <h2>Satele Shan</h2>
                        <img src="../images/jedi-master/satelleshan.png" alt="">
                        <p>Satele Shan is a Human female Jedi Master and the youngest Jedi to ever become Grand Master of the Jedi Order. She was born on Brentaal and is a direct descendant of the legendary Jedi Masters Bastila Shan and Revan. Jedi Master Dar'Nala believed that she possessed a "gift" similar to that of her ancestor.</p>
                        <h3>Biography</h3>
                        <h4>Early life</h4>
                        <p>Renowned for her great wisdom and powerful connection to the Force, Master Satele Shan is the voice and conscience of the Jedi Order. She is a direct descendant of Bastila Shan, the legendary Jedi who battled Darth Revan centuries ago - as well as being the descendant of Revan. Unlike her brash and arrogant ancestor, Master Satele—who prefers being addressed by her first name—possesses a warm demeanor and approachable personality. This relaxed and unassuming attitude belies her true strength and determination. Master Satele is a veteran Jedi warrior who has repeatedly confronted the power of the dark side and survived.</p>
                        <p>Master Satele bravely fought the resurgent Sith Empire during her Padawan years, playing a key role in several major battles during the Great Galactic War. She cemented her position among the Jedi when she rediscovered the long-lost world of Tython and helped found a new Jedi Temple there to replace the one destroyed on Coruscant. Since the Republic signed the Empire’s treaty, Master Satele has worked tirelessly to preserve that fragile peace, preventing multiple attempts to reignite the conflict. However, she knows all too well that light and dark cannot coexist forever.</p>
                        <h4>Fall of Korriban</h4>
                        <p>By the time the Sith had returned, Satele was stationed on board a space station with her Master. The station had just intercepted a smuggler carrying Sith artifacts. While escorting him to a holding cell alongside Darach and Corporal Jace Malcom, Satele sensed "A great darkness". At that moment, Sith cruisers emerged from hyperspace, and began an assault on the space station. Knowing that the battle was lost, Darach's new mission was to warn the Republic about the Sith's return.</p>
                        <p>Without a ship fast enough to outrun the Sith starfighters, there was only one option: use the captured smuggler's ship to evade the onslaught. Heading to the hangar, Satele and Darach soon cleared it, while Malcom and the smuggler covered the rear. After Malcom locked the door, a new threat entered the hangar: a Fury-Class Imperial Interceptor landed. The boarding ramp descended and Lord Vindican and Darth Malgus emerged. Seeing the threat, Darach told Malcom and the smuggler to prep the ship. Satele and Darach engaged the Sith, but they were soon overpowered. Malcom fired a missile at Vindican, which he effortlessly blocked. Satele was then told to escape, as she was to "walk a different path". Darach then left to battle with the two Sith alone. Satele threw her Master her own saberstaff, then leaped aboard the ship. Immediately, she was told to man the onboard turret to destroy any inbound threats. While shooting down Sith starfighters, she eventually felt a death convulsion, and accepted the truth: Darach had died valiantly fighting Malgus. After the smuggler pulled a risky maneuver by flying through an opening in one of the Sith ships, the ship jumped to hyperspace.</p>
                        <h4>Battle of Alderaan</h4>
                        <p>Satele was present during the Battle of Alderaan. She joined the battle with the Republic reinforcements, after almost all of the Republic troopers who were stationed on the planet were either captured or killed.</p>
                        <p>She came to the rescue of Jace Malcom seconds before he was to be executed. She repelled the Sith Warriors that were holding him with a Force Wave. She then charged toward Darth Malgus and after cutting through the thick Sith lines, she engaged him in lightsaber combat with a saberstaff. After clashing for a few moments, Malgus managed to strike Satele, forcing her to fall on her knees. Guarding herself, She then Force-pulled a tree and collapsed its trunk, forcing the Sith to disengage to avoid being crushed. The two force-users then started battling again, on top of the fallen tree.</p>
                        <p>Malgus soon Force-pushed Satele into another tree, going in for the killing blow. Satele, however, was able to jump above him. Malgus took this moment of vulnerability to cut through the hilt of Satele's double-bladed lightsaber. He then went in for another killing blow. Without a lightsaber Satele had very few options. Weaponless, Shan saved herself by channeling The Force itself, stopping Darth Malgus' lightsaber with her bare hands.</p>
                        <p>Malcom then charged the Sith Lord and they scuffled for a few seconds. Reaching a stalemate in their fight, Malcom revelead an activated thermal detontator in his hand. The blast threw both of the combants backwards, Malgus being the first to rise. Satele then stepped in and Force-pushed Malgus into a rock face. As Malgus attempeted to resist the force push, Satele launched a stronger Force-push, that completely obliterated the rock face, defeating him. She then walked back over to Malcolm, who launched a flare into the air to signal that there were survivors of the Sith attack.</p>
                        <h3>Personality</h3>
                        <p>Confidence, and resolute calm throughout her life that is far beyond her short stature. In her youth, Satele who preferred to be addressed by her first name, even as a Jedi Master, Satele inherited her ancestor Bastila's impatience and impetuousness, though those aspects of her personality were later tempered under the tutelage of Master Dar'Nala. Satele is a powerful presence on the battlefield, and her reputation as one of the greatest heroes of the Republic is directly inspired by her actions in the Battle of Alderaan.</p>
                        <p>As a Jedi Knight, Satele is sworn to serve the Republic, and her devotion to her cause and her selflessness drove her to give up the chance at a normal life and a family when she had her son Theron. This same sense of duty, coupled with her fear of the dark side's corrupting influence, had caused her to break off her relationship with Theron's father several months earlier. Satele recognized the fact that she would do everything in her power to protect her son, and coupled with the powers and responsibilities she possessed as a Jedi and a Republic hero, she believed the risk is too great and therefore gave Theron to Ngani Zho. Ngani Zho himself was a paternal figure to her, and as a result Satele felt that he is the only person she could trust enough to tell about her pregnancy. of All of his many students, Ngani felt that Satele is the one who made him the most proud, and she is greatly saddened by her Master's passing. However, despite her Jedi teachings and devotion to placing the galaxy's needs over her own, Satele deeply regretted ending her relationship with Malcom and giving up her son, and the memories that are dredged up after meeting her son as his mother for the first time are still painful even twenty-six years</p>
                        <h3>Powers and abilities</h3>
                        <h4>Force powers</h4>
                        <p>As the descendant of Revan and Bastila Shan, two of their generation's most powerful Jedi, Satele is incredibly strong in the Force. Satele is skilled with the use of telekinesis, and her strength with such abilities even as a Jedi Knight is enough for her to bring down an entire mountain on top of Darth Malgus during their battle. She is also able to dismantle the door to Darth Mekhis' fortress using the Force, and is skilled enough with tutaminis abilities to block a lightsaber blade with her bare hands without injuring herself. Satele's powers continued to grow over her lifetime; by the time of the Battle of Rhen Var, she is able to destroy a blast door simply by using the Force to break it into pieces.</p>
                        <p>During the incident on Sebaddon she is able to dismantle hex droids with a mere gesture-droids that are more than a match for other Jedi and Sith alone. Throughout her life, Satele is known for her affinity for foresight-she is able to predict the arrival of the Sith Empire at Korriban, and her ability to view the future grew stronger over the course of her life. By the time of the renewed war with the Sith, many Jedi believed that the Grand Master could change the future simply by predicting it. Satele is also an accomplished telepath to the point where she could both read the minds of others and communicate in full sentences with them. She is able to influence the biological components of more than half a dozen hexs to keep them at bay, though Satele could not influence the hexes and maintain a Force shield strong enough to seal in the air around her at the same time for long. Satele's master Dar'Nala suspected that she had inherited her ancestor Bastila's skill with battle meditation, though her suspicions are never confirmed. The Grand Master also developed a strong bond with her apprentice through the Force, allowing her to sense Shigar Konshi's emotions from halfway across the galaxy.</p>
                        <h4>Combat skills</h4>
                        <p>Trained by the Order's Battlemaster Kao Cen Darach, Satele is exceptionally skilled with the use of both a normal lightsaber and a double-bladed lightsaber. She utilized a blue-bladed saberstaff in the years before the Great Galactic War, though it was destroyed when Kao Cen utilized it and his own blade in battle with Vindican and Malgus. By the year 3,667 BBY, Satele was utilizing a second blue-bladed saberstaff, though she again lost this weapon when Darth Malgus cut it in half during the Battle of Alderaan. She quickly constructed another blue double-bladed saber, though she eventually exchanged it for a single-blade green lightsaber sometime during the Cold War and utilized that weapon during the Sebaddon affair in 3,643 BBY. However, she exchanged it for another double-bladed saber by the time of the conflict with the Flesh Raiders not long afterwards. In combat, Satele is an agile fighter who utilized acrobatics to both evade her opponents and to quickly strike them down.</p>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 
  <?php include '../bottom.php'; ?>