
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>sidious</title>
    <link rel="stylesheet" href="../css/bootstrap.css">
    <link rel="stylesheet" href="../css/styles.css">
    <?php include '../cookie.php';
    ?>
   
   
</head>
<body>

<?php include '../top.php'; ?>
<div class="icon">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title">
                    <div class="info">
                        <h2>Darth Sidious</h2>
                        <img src="../images/sith-lord/sidious.jpg" alt="">
                        <p>Darth Sidious, born Sheev Palpatine and also known simply as the Emperor, was a human male Dark Lord of the Sith and Emperor of the Galactic Empire, ruling from 19 BBY to 4 ABY. Rising to power in the Republic Senate as the senator of Naboo, the secretive Sith Lord cultivated two identities, Sidious and Palpatine, using both to further his political career. He orchestrated the fall of the Galactic Republic and the Jedi Order through the Clone Wars, and then established his reign over the galaxy which lasted until his death at the Battle of Endor. However, the dark side of the Force gave rise to powers which allowed the Emperor to return from the grave.</p>
                        <p>Born on the Mid Rim planet Naboo around 84 BBY during the Republic Era, Sidious possessed a strong connection to the Force, and was secretly trained in the ways of the Sith by Darth Plagueis. He eventually killed his Sith Master in order to train his own Sith apprentice, Darth Maul, for the Rule of Two limited their ranks to two Sith Lords at any given time. As a result of the Invasion of Naboo, a crisis orchestrated by Sidious, the Senate elected Palpatine as Supreme Chancellor. The Separatist Crisis and the Clone Wars were masterminded by Sidious and his new apprentice, Darth Tyranus, in an effort to achieve galactic dominance. Following an attempt to arrest the chancellor, the Great Jedi Purge commenced with Sidious enacting Order 66.</p>
                        <p>With the Jedi all but extinct, Sidious installed the New Order in the Republic's place, declaring himself Galactic Emperor and bringing an end to a millennium of democracy. He had also taken another new apprentice, having lured the Jedi Knight Anakin Skywalker to the dark side and transforming him into Darth Vader. Their reign was virtually unchallenged for a generation until the formation of the Alliance to Restore the Republic. During the Galactic Civil War, the Emperor sought to replace Vader with his son, Luke Skywalker. However, Sidious' plan backfired when Vader ultimately renounced the dark side and killed Sidious to protect Luke. Thus, with the Sith's destruction, the Force was brought back into balance, fulfilling Anakin's destiny as the prophesied Chosen One.</p>
                        <p>Through his master's teachings, however, Sidious transferred his essence to an imperfect clone vessel that had been modeled on his original body. Anticipating the possibility of defeat, he created the Contingency to destroy the Galactic Empire and replace it with a new Sith Empire, in the event of such a setback. His plans culminated in the destruction of the New Republic and the emergence of the First Order, the creation of Supreme Leader Snoke, who turned Ben Solo—heir to the Skywalker bloodline—to the dark side, and the establishment of the Final Order. When the Emperor announced his return to the galaxy in 35 ABY, the Resistance invaded the planet Exegol, Sidious' hidden stronghold in the Unknown Regions. During the battle, he discovered a dyad in the Force in the form of the bond between Solo and Rey, a Jedi apprentice sired from the Emperor's bloodline. His ambition of eternal rule was finally quashed when Rey called upon the strength of past Jedi to vanquish her grandfather by turning his own power against him, destroying Sidious and his Sith Eternal cultists.</p>
                        <h3>Biography</h3>
                        <p>The origins of Darth Sidious were closely guarded secrets that he took to his grave more than once. He was born on the Mid Rim planet Naboo as Sheev Palpatine, approximately eighty-four years before the Battle of Yavin. The noble Palpatine family belonged to the affluent class in Naboo society, although by the time of the Imperial Era Palpatine did not have a family as far as the public was aware. Palpatine was raised in the cultured city of Theed, his homeworld's capital; he formed connections with a reputable host of credible politicians produced over the centuries, all the while acquiring a great amount of knowledge on governance and the subtleties of power during his youth.</p>
                        <p>The details about how Palpatine came to study under the Sith are known by very few, with it not even being known of when he did. But he became the Sith apprentice to Dark Lord of the Sith Darth Plagueis and took on the name Darth Sidious. Now known as the Sith Lord Sidious, he learned all his Sith Master knew about the dark side of the Force and studied the Force as their predecessors, including the ancient Darth Bane, knew it. While apprenticed to Plagueis, Sidious constructed his own Sith lightsabers.</p>
                        <p>While training with Plagueis, Sidious was taught that two Sith were required for their perilous machinations. So, if they worked together in accordance to Darth Bane's Rule of Two, with one of them serving as bait for the dark side of the Force and the other as a vessel, they would succeed in acquiring the ability to harness the full power of the dark side and rule immortal for ten thousand years.</p>
                        <p>Darth Sidious and Plagueis worked together for years, trying to unlock the secrets to immortality. Sidious was eventually made aware of Plagueis' ability to manipulate the midi-chlorians to create life, which his master employed to prevent the people he cared for from dying. However, Plagueis ultimately discovered a secret to cheat death, which Sidious later stole: the ability to transfer his own consciousness to another body, using bodies as vessels. This obsession with extending one's own life later passed onto Sidious from his time as Galactic Emperor. Plagueis also attempted to create a Force dyad with Sidious, a unique Force-bond as strong as life itself and which inspired the Rule of Two. However, Plagueis was unable to form the dyad.</p>
                        <p>In his public persona as Sheev Palpatine, his embarkment on a career in politics was aided by his master, who raised him to the position of Senator for his homeworld in the Senate of the Galactic Republic. Once elected, the representative for Naboo quickly joined incumbent Supreme Chancellor Skor Kalpana's ruling party, and noticed the fervent bickering and corruption that mired the Republic. He began to establish relations with those who'd become his future collaborators, such as Wilhuff Tarkin. The duo met for the first time when Tarkin was still a cadet of the Sullust Sector Spacefarers Academy, and while Palpatine was still apprenticed to Plagueis. Taking an interest in the younger man, Senator Palpatine resolved to help him to join the Judicial Department, according to Tarkin's desire but advised him to also consider a political career. In the following years, their relationship became more and more confidential. Palpatine often lauded Tarkin for his talents and skills and remarked they were very similar: they both came from planets at the edge of the galaxy but were destined to have great repercussions on the history of the galaxy itself. Tarkin eventually became one of the few people who called Palpatine by his first name.</p>
                        <p>Keeping his Sith identity a secret from the public eye, Sidious took it upon himself to execute the Sith's long-percolating plan of supplanting the Republic with a new Sith Empire as well as destroying the Jedi Order. Seeking a Sith apprentice, Sidious traveled to the planet Dathomir and met with the Dathomirian Nightsister Mother Talzin. Intermingling his knowledge of the dark side of the Force with Talzin's knowledge of Nightsister magicks, Sidious had considered to make Talzin his apprentice and right hand. However, Sidious chose her infant son, the Zabrak Nightbrother who would become his true Sith apprentice, Darth Maul.</p>
                        <p>However, by taking Maul under his wing, the Rule of Two had been violated,[source?] as it demanded only two Sith. Following the traditions set forth by the Rule of Two and deciding that Plagueis had outlived his usefulness, Sidious betrayed and murdered his master in his sleep. Now the Sith Master himself, Sidious brutally trained Maul to be a weapon of the Sith, viewing Maul's prowess and combat abilities as an invaluable asset to his master plan. Preferring a mysterious, hooded presence through holographic transmissions rather than direct communication, Sidious contacted the galaxy's most powerful beings and convinced them to do his bidding with promises and threats. To that end, Sidious was also able to manipulate Nute Gunray's rise to the position of Viceroy of the Trade Federation. Sidious also helped the Geonosian Poggle the Lesser rise to the position of Archduke of Geonosis and controller of their droid foundries. With Sidious's backing, Poggle produced millions of B1-series battle droids for the Trade Federation military.</p>
                        <h4>Search for Immortality</h4>
                        <p>During the Imperial Era, secure in power as Emperor of the galaxy, Sidious pursued his obsession with immortality, and mostly withdrew from the public eye to probe the secrets of the darkside and study his Sith arcana extensively to unlock the ability to live forever. He prepared the ancient Sith world of Exegol, constructing a base of power within the Sith Citadel located on the surface, planning to claim the ancient throne of Sith as his permanent seat of power. His loyal cult following, the Sith Eternal, began to experiment with technology and genetic cloning science to expand his lifespan. Exegol was also home to his most promising experimentations within a vergence of the Force.</p>
                        <h4>From the shadows</h4>
                        <p>Sidious' followers venerated his efforts to bring about a New Empire and labored to rebuild the Empire from Exegol as a true Sith Empire. To this end, Sidious' underlings crafted a vast armada of planet-killing warships, the Final Order. From the shadows, Sidious plotted his return to power, and forged the remnants of the Empire into the First Order while he manipulated the New Republic. Once deployed from Exegol, the Final Order would bolster the forces of the First Order military, allowing the regime to finalize its subjugation of the galaxy. Sith loyalists served on the executive boards of corporations such as Kuat-Entralla Engineering and Sienar-Jaemus Fleet Systems, which allowed them to funnel assets critical to their domineering machinations through subsidiaries to Exegol. Under Sidious, the children of the Sith Eternal were raised to covet the religion of the Sith, while being ingrained with the utmost loyalty to their Emperor. Their efforts yielded legions of Sith troopers, soldiers trained to be fanatically loyal to the Sith via flash imprinting technologies built upon the Kaminoan techniques in the training of clone troopers. The efforts of the Sith Eternal led to the creation of a fleet and army which would spell the end of freedom in the galaxy were they to escape into hyperspace.</p>
                        <h4>Legacy</h4>
                        <p>Given the amount of power required to forever destroy Sidious, Rey died after vanquishing the Emperor. However, Solo emerged from the pit where the Emperor had previously flung him and gave his remaining life energy to revive Rey, whom he shared a kiss with before he vanished into the Force as the last of the Skywalker bloodline. Despite her Sith lineage as Sidious' descendant, Rey renamed herself "Rey Skywalker" to honor the family of her masters.</p>
                        <p>Following the Battle of Exegol, the galaxy celebrated Sidious' death and the defeat of the Final Order, with uprisings against the weakened First Order taking place on several planets. Bespin, Jakku, Corellia, Lothal, Thyferra, Endor, Coruscant and even Sidious' native Naboo were amongst the systems reported to be openly rebelling against his forces.</p>
                        <p>During the victory celebration at the Ajan Kloss Resistance base, Finn and Poe Dameron discussed the possibility of Sidious coming back once more, given that he came back more powerful than ever following his defeat at Endor. They concluded that while Sidious could perhaps return yet again, some other evil would arise as evil always rises, though not for a long time.</p>
                        <h3>Personality and traits</h3>
                        <p>Prior to the Galactic Empire, Darth Sidious was careful to put on a charade, presenting himself as a grandfatherly gentleman and a servant of the public good. When in character, he often spoke of himself with great modesty and maintained only as much luxury as was expected of someone of his stature. However, Sidious was, in fact, a skilled manipulator and strategist, having orchestrated countless events in the galaxy, from the Invasion of Naboo to the Clone Wars, with the sole aim of increasing his own power. Even when something occurred that he did not initially plan for, the Sith Lord demonstrated that he was as adept at improvisation as he was at plotting.</p>
                        <p>After his ascension to Galactic Emperor, he essentially dropped his public persona and started living as Sidious full-time. Despite this, very few people other than Vader and some Royal Guard members knew that the Emperor was a Sith, as he took great pains to hide his capabilities. Even Grand Moff Wilhuff Tarkin, perhaps Sidious's most trusted servant besides Vader, only suspected that Sidious was a Sith. Sidious also regarded Gallius Rax as a confidante and allowed Rax to address him as "Sheev." Freed from having to portray his gentle alter-ego, Sidious allowed his true personality, one of great cruelty and sadism, to occasionally shine through in ways that were obvious even to the most sycophantic of his servants. This caused many of those who worked closely with him, such as Senator Orn Free Taa and some of the Empire's intelligence chiefs, to greatly fear him. Sidious was also known to loath ostentation and luxury.</p>
                        <p>Sidious' most defining trait was his deeply manipulative nature, seducing many parties with promises of power, prize, even salvation to further his agenda. He successfully manipulated the leaders of the Separatists and Count Dooku under the pretense of a better future, coerced Anakin Skywalker into becoming Darth Vader by promising to save his beloved, Padmé Amidala, attempted to sweet talk Bridger with being able to reunite with his deceased parents by altering fate and also tried to push Luke Skywalker into murdering his father so they could rule the galaxy together. While trying to steer Bridger, he displayed himself in his public personality via hologram, showing himself as benign and polite. Once Bridger frustrated his plans, his true malignant self was revealed as he had underestimated the boy's hatred for the Empire and devotion to the Rebellion and new-found rebel family. Likewise, when Sidious tried to motivate Luke into killing his father upon momentarily embracing the dark side of the Force, the young Skywalker desisted due to his love to his father and Jedi teachings, which led Sidious to turn on him before Vader stopped him from harming his son.</p>
                        <h3>Power and abilities</h3>
                        <p>As the reigning Dark Lord of the Sith in his time, Darth Sidious was extraordinarily powerful in the Force, with extreme levels of mastery over the powers of the dark side. He was extremely skilled in Force lightning, and was known to use it as his signature force power, both as a deadly attack, and as a means of torture. On several occasions on Ryloth, he utilized blasts of Force lightning powerful enough to not have only killed the lyleks on contact, but also badly charred and scorched their carapaces, which were tough enough to repel heavy blaster fire. On another occasion, he used the ability to damage a Twi'lek freighter's engines badly enough to pull it out of the sky with telekinesis. Sidious could use Force lightning in a number of ways, including striking multiple enemies at once, with the bolts jumping from one victim to the other, like a chain and imbuing the ground around a victim's feet with energy, effectively electrocuting them. His Force lightning's raw power was demonstrated to be far greater than that of Dooku's; while Yoda was able to effortlessly absorb and deflect Dooku's lightning, he was only able to partially deflect Sidious's. Another more obscure ability that he possessed was the power to produce a dark aura, a miniature storm of malevolent Force energy that slowed the movement of and tortured all that it caught within its radius. The maximum potential of Sidious's Force lightning, however, was achieved before his final death on Exegol; when restored back to his former self, Sidious unleashed an immense wave of Force lightning towards the sky which rapidly expanded enough to disable all the ships of the Resistance.</p>
                        <p>He was also highly skilled with telekinesis; during his duel with Yoda, he levitated several Senate pods simultaneously, including the one he was standing on, with great dexterity and accuracy. Likewise, he was skilled enough with telekinesis that he was also able to remove Luke Skywalker's handcuffs while barely having to lift even a finger when they met face to face on the second Death Star. Sidious was capable of unleashing a Force push strong enough to easily send Maul and Opress flying and he was able to keep them pinned with little effort. He later effortlessly slammed Maul into the ground and walls, badly wounding him. Sidious was also highly skilled with Force choke. When he arrived on Mandalore, he was effortlessly able to telekinetically throttle two Mandalorians to death at once and used this power on two others while standing on the other side of the room that they were in. He was even able to use his abilities on a target from hundredw him his target, allowing him to telekinetically choke and pick up Count Dooku and open the handcuffs of Bridger while projecting himself to their respective locations through the use of a hologram.</p>
                        <p>Darth Sidious was exceptionally adept at foreseeing the future, an ability which allowed him to plan for nearly any contingency.[90] He believed that, with enough time and practice, he would eventually have been able to use the dark side to view the future with infallible accuracy. The Dark Lord also was proficient in Sith magic, as he was able to cast a Dark illusion on Yoda using a ritual that applied Balc speech incantations and managed to access the World between Worlds using an unknown ritual. He was also capable of using Sith magic to generate a blue fiery energy, which he used to attack Ezra and Ahsoka, that he can use both as a weapon and a tool in order to bind and draw someone closer, as it did with Ezra; the energy wrapping around his leg and becoming akin to a tangible rope as well as knowledge of the ancient Sith tongue, ur-Kittât. The Dark Lord was also adept in the use of Force Persuade to such an extent that he was able to take complete control of a subject's mind and force them to obey his commands.</p>
                        <p>Likewise, Sidious was also capable of using Dark Absorption. He was also capable of telepathically communicating with Darth Vader over a distance of hundreds of light-years. It appeared, however, as though this ability may have been limited to sending and receiving relatively simple messages such as Vader requesting that a starfighter be shipped to him, as the two Sith Lords communicated through holoprojections while discussing more complex matters. Sidious also had a remarkably keen ability to sense the thoughts and feelings of others, including those of incredibly powerful Force adepts such as Darth Vader and Luke Skywalker. On a related note, he was also capable of hiding his own thoughts and feelings from even such individuals as Yoda, and managed to conceal his true dark nature from the entire Jedi Council for decades before deliberately revealing himself. Sidious also used Force Dash. He even created the extremely powerful Force-wielder Snoke, who far surpassed Kylo Ren and Rey. He was able to easily overpower both Ben Solo and Rey, as shown by how he deactivated their lightsabers and disarmed them using the Force, then later easily telekinetically picked up the former and threw him into the pit behind him. Palpatine also demonstrated the ability to drain life essence or the Force from his victims as he did with Rey and Ben Solo in their confrontation on Exegol.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 
  <?php include '../bottom.php'; ?>