
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>luke-skywalker</title>
    <link rel="stylesheet" href="../css/bootstrap.css">
    <link rel="stylesheet" href="../css/styles.css">
    <?php include '../cookie.php';
    ?>
   
   
</head>
<body>

<?php include '../top.php'; ?>
<div class="icon">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title">
                    <div class="info">
                        <h2>Luke Skywalker</h2>
                        <img src="../images/jedi-master/luke.jpg" alt="">
                        <p>Luke Skywalker was a Force-sensitive Human male who helped defeat the Galactic Empire in the Galactic Civil War and helped found the New Republic, as well as the New Jedi Order.</p>
                        <p>Born in 19 BBY as the son of the fallen Jedi Knight Anakin Skywalker and the Queen and Senator of Naboo, Padmé Amidala, Luke was raised on Tatooine and hidden from Emperor Palpatine and his father, who had recently become Darth Vader, Dark Lord of the Sith. In 0 BBY, Skywalker's life changed forever. A chance purchase of two droids, R2-D2 and C-3PO, led to him to receive training in the ways of the Force from Jedi Master Obi-Wan Kenobi and to meet Han Solo, and Princess Leia Organa, who was, unbeknownst to him, his twin sister. Skywalker then destroyed the first Death Star and joined the Rebel Alliance.</p>
                        <p>Over the next few years, he fought in many of the most important battles of the Galactic Civil War, helping to found Rogue Squadron and fighting Imperial forces across the galaxy. In 3 ABY, Skywalker received Jedi training from Yoda, and learned from Vader that the Sith Lord was his father. One year later, he fought in the Battle of Endor, and succeeded in turning his father back to the light. Thanks to Skywalker, Palpatine was killed, and the Empire was dealt a crippling blow. One year later, the New Republic was formed.</p>
                        <p>Throughout the succeeding decades, Skywalker helped keep peace throughout the galaxy as the New Republic slowly defeated small remnants of the Empire. When Palpatine returned in the form of several clone bodies, Luke temporarily fell to the dark side and became the resurrected Emperor's apprentice. He was later redeemed with the help of his friends, and continued with his goal of reviving the Jedi Order. In 11 ABY, he founded the New Jedi Order, and began teaching Force-sensitives about the ways of the Force at the Jedi Praxeum, fulfilling his destiny as the first of the new Jedi. In the midst of this rebirth came numerous challenges for Skywalker and his apprentices, including the Black Fleet Crisis, the Almanian Uprising, and the lure of Waru, but Skywalker, aided by fellow Jedi and his friends, was able to overcome each trial. Meanwhile, after a long series of failed relationships, Luke married fellow Jedi and former Emperor's Hand Mara Jade in 19 ABY.</p>
                        <p>Several years after the conclusion of the Galactic Civil War, Skywalker found himself, yet again, on the front lines. Skywalker served as the leader of the New Jedi Order, during the Yuuzhan Vong War, an invasion by the extra-galactic Yuuzhan Vong species. During the war, Skywalker's wife gave birth to a son, who they named Ben, in memory of his first mentor of the Force: Ben Kenobi. Skywalker endured countless battles as the New Republic was first pushed back, including the fall of his home on Coruscant. However, the newly reformed government, labeling itself the Galactic Federation of Free Alliances, regrouped and helped push back the alien invaders. In the final stages of the war, Skywalker sought out the living world of Zonama Sekot, convincing the planet to join the Galactic Alliance in a final battle on Coruscant, in which Skywalker personally led the assault on Supreme Overlord Shimrra Jamaane's citadel and slew Jamaane. Combined with the fact that his nephew, Jacen Solo, would soon after kill Jamaane's puppet master, Onimi, the Yuuzhan Vong were defeated and the war was ended.</p>
                        <p>After the Yuuzhan Vong War, Skywalker maintained a prominent role among the Jedi into the Dark Nest Crisis, which saw him call a Jedi convocation to deal with strife within the Order. Faced with disunity, Skywalker assumed the title of Grand Master and direct control over the reestablished Jedi Council. Despite the successful handling of the Dark Nest Crisis and the Swarm War, lasting peace was yet to be achieved, as the Second Galactic Civil War broke out a few years later. Skywalker was plunged into a dark time as his nephew, Jacen Solo, became a Sith apprentice under his old adversary Lumiya and slew his beloved Mara. His grief was further compounded by his son's treading near the dark side as well, but he continued to lead the Jedi, forming the Jedi Coalition to oppose the rule of the Alliance by his nephew, now a Sith Lord by the name of Darth Caedus. With Skywalker's aid, Caedus was killed by his twin sister Jaina, ending the war and restoring peace to the galaxy.</p>
                        <p>In the aftermath of the war, Natasi Daala ascended to the position of Chief of State and fostered a wide spread anti-Jedi sentiment resulting in tensions between the Jedi Order and her government. Daala ultimately had Skywalker arrested for dereliction of duty, and in exchange for his freedom, he was exiled and forbidden from involving himself in the affairs of the Jedi Order. Skywalker and his son embarked on an odyssey across the galaxy in order to discover the causes of Jacen Solo's fall to the dark side. During their journey, the Skywalkers encountered the Lost Tribe of Sith, as well as a malevolent dark side entity known as Abeloth. With the help of his son and the rest of the Jedi, Skywalker returned to his position as Grand Master. Skywalker and his allies then repelled the Sith threat, and with the help of an unlikely Sith ally, defeated Abeloth, preventing another disaster that could endanger the galaxy.

                        Eventually, Luke passed away, and became one with the Force.</p>
                        <h3>Galactic Civil War</h3>
                        <p>The purchase of two droids by Skywalker's uncle changed the youth's life forever. With the discovery of a desperate message to Obi-Wan Kenobi contained within the astromech droid R2-D2, Skywalker soon found himself in the company of Kenobi after being attacked by Sand People. Kenobi then revealed to Skywalker that he had once been a Jedi Knight who served in the Clone Wars with Skywalker's father. He went on to inform Skywalker that his father was no cargo pilot, but a Jedi Knight struck down by Darth Vader.</p>
                        <p>Soon after, Skywalker and Kenobi came upon a group of slaughtered Jawas—the same ones who sold the droids to Owen Lars. Luke deduced from learning that Imperial stormtroopers were responsible that they might have looked into the sales records of the droids, and rushed home in the hopes of saving his aunt and uncle. Upon quickly returning home, Skywalker discovered that he was too late: his aunt and uncle had been murdered by Imperial stormtroopers looking for R2-D2 and C-3PO. With his family dead, he agreed to accompany Kenobi to Alderaan to deliver the astromech, who was carrying the plans for the Death Star, to Bail Organa at the behest of Organa's daughter, Princess Leia Organa. The two traveled to the Chalmun's Cantina to obtain passage off the planet and met Han Solo and his first mate Chewbacca. Skywalker nearly had a fatal run-in with Ponda Baba in the cantina. Obi-Wan brokered a deal to pay Solo two thousand credits up front plus fifteen more when they arrived on Alderaan. Luke sold his speeder to pay for the two thousand up front.</p>
                        <h3>The trials of a Jedi Master</h3>
                        <p>In 11 ABY, Luke Skywalker, now a Jedi Master, felt that, due to the growing dangers in the galaxy, the New Republic needed a New Jedi Order to serve and protect it. He proposed to the government that a new Jedi Academy needed to be started, with himself as its head instructor. When the New Republic agreed, Skywalker began searching in earnest for Jedi candidates to train in the Great Massassi Temple on Yavin 4 where he had established his Jedi Praxeum. One of the first places Luke went to was Eol Sha, a harsh volcanic world inhabited only by a small colony. Their leader, Gantoris, was at first convinced that Luke was the "dark man" of his dreams, a man that would only lead him to destruction with promises of power. Because of this, he made Luke pass several tests, such as collecting fungi in a steam vent and walking across lava while battling a giant lava snake. Passing the tests, Luke convinced Gantoris to join the Jedi Order and also arranged for the Eol Sha colonists to be transported to Dantooine, which had a much more hospitable climate. After further searching, Luke found his next apprentice, Streen, on an abandoned gas prospecting platform on Bespin. Streen agreed to join the Jedi on the condition that Luke would teach him to quiet the "voices" and emotions in his head that he "heard" from those around him.</p>
                        <p>Another student at the new academy was Kam Solusar, a former Dark Jedi who Luke had turned back to the light during the reborn Emperor's return. Another one of Luke's students, Corran Horn, sought him out to learn to use the Force to rescue his wife, at Luke's suggestion, under the alias of Keiran Halcyon. Some of Luke's other students included the clone Dorsk 81, the Dathomiri Kirana Ti, and the historian Tionne. In the early years, Luke's Jedi Knights also included Brakiss, Madurrin, Kyle Katarn, Cilghal and Kyp Durron. Mara Jade also studied under Luke in a less official capacity. In future years, Luke's Academy was to train notable Jedi such as Jaden Korr, Rosh Penin, Tenel Ka, Zekk, and his niece and nephews Jaina, Jacen, and Anakin Solo. Luke's students in turn eventually became Masters, and a new generation of Jedi Knights arose. One Jedi who never attended the academy was Tyria Sarkin, who, over a period of years, developed her Force skills and earned Jedi Knighthood from Luke. Through this academy, Skywalker returned the Jedi Order to the galaxy, and began to reverse the damage done by Palpatine and Vader in previous decades.</p>
                        <p>However, galactic circumstances kept Luke from being completely devoted to the Jedi Academy. Early on, Luke was called away from the academy to find Han and Chewbacca, who had disappeared after embarking on a mission to Kessel. Luke along with his old friend Lando traveled to Kessel disguised as businessmen, and confronted Moruth Doole, administrator of the spice mines. The two retrieved the Falcon from Doole's clutches, for the Rybet had stolen it and sent Han and Chewbacca to the spice mines. Luke and Lando fled from Doole's large ragtag fleet, and headed for the Maw Cluster, when suddenly the Sun Crusher, with Han, Chewbacca, Qwi Xux, and Kyp Durron aboard, shot out of the cluster, closely pursued by Admiral Daala's fleet of Imperial Star Destroyers. The Millennium Falcon and the Sun Crusher escaped as the Imperial fleet engaged Doole's forces in an impromptu brawl.</p>
                        <p>Sometime during the New Republic's rule, Luke helped X2, a Force-sensitive clone trooper whom he had trained as a Jedi several years earlier, find his brother X1, now a Sith Lord. During the Battle of Vjun, Luke gave his student instructions and advice. While guiding X2 through Bast Castle, Skywalker was disturbed by bad memories due to the fact that the fortress had previously belonged to Darth Vader. Luke later tracked down X1 to his base on Mustafar but was captured by the Sith, who wanted to create an army of Dark Jedi clones using Skywalker as a template. In the ensuing battle, X2 rescued Luke and killed X1. For his gratitude, Skywalker made X2 a Jedi Master.</p>
                        <h3>Personality and traits</h3>
                        <p>In his youth, Luke was often impatient, looking ahead to the future with little regard for his present surroundings. Like his father, he was impulsive, reckless, and often had little regard for his own personal safety.[7] According to Han Solo, his first impression of Skywalker was a naïve kid who needed to be taught a thing or two.</p>
                        <p>However, as his skills in the Force progressed and after losing a hand to Darth Vader, Luke became more patient and seasoned, and was often seen as having wisdom beyond his years. However, he still retained his idealistic worldview of his youth, believing that Vader was redeemable. This belief would stay with him for his entire life, as he would go so far as to spare the Sith Lumiya because he believed she could be redeemed, despite the fact there was much evidence to the contrary and a pressing need to have her eliminated. Some called Skywalker naïve for this, although it was actually his kindness and ability to see the good in others that forced him to view others this way. This somewhat soft stance on discipline and errant behavior at the Jedi Praxeum indirectly led to the attacks by the spirit of Exar Kun on his students.</p>
                        <p>Luke, especially after serving the reborn Darth Sidious as the Sith Lord's apprentice, was often conflicted about his role in the Force and had his judgment clouded, until Mara Jade and Corran Horn helped free him of the dark side's influence. This type of inner conflict would reemerge in the Yuuzhan Vong War, where Luke struggled with how the Jedi should approach the war.</p>
                        <p>Luke was known for being empathetic to his friends and would go to great lengths to help them, whenever he could. At some times, he could be almost passive, serene—a result of his mastery of the Force that allowed him to remain calm and in control even in the heat of battle. His loyalty and devotion to his comrades was virtually unshakable, Darth Sidious tried to sever his connection to his friends during their confrontation on board the second Death Star, but ultimately failed. Luke's love for his friends and his determination foiled the plans of the evil Sith Lord.</p>
                        <p>After the death of his wife Mara Jade Skywalker, Luke felt that his world had ended. The weight of his grief would burden him even as the Jedi Order looked to him for leadership and his son Ben fell perilously close to the dark side of the Force. However, Luke would eventually accept that his duty was to lead the Jedi and he returned to the forefront of the order, leading a series of missions against the Sith Lord Darth Caedus.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 
  <?php include '../bottom.php'; ?>